Initialize project 0 for agents

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -2,9 +2,9 @@ name: CMake Build Matrix
 
 on:
   push:
-    branches: [master]
+    branches: [bot]
   pull_request:
-    branches: [master]
+    branches: [bot]
 
 env:
   BUILD_TYPE: Debug
@@ -78,3 +78,11 @@ jobs:
       - name: Check Tests
         working-directory: ${{github.workspace}}/build
         run: make build-tests && make check-public-ci-tests
+
+      - name: Check Project 0
+        working-directory: ${{github.workspace}}/build
+        run: |
+          not_tidy=0
+          make check-clang-tidy-p0 || not_tidy=1 # do not fail fast.
+          make count_min_sketch_test && ./test/count_min_sketch_test
+          exit $not_tidy
